[package]
name = "cab"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1.5.4"
once_cell = "1.8.0"
rand = "0.8.4"

[dependencies.curl]
version = "0.4.38"
default-features = false
features = ["mesalink"]